# Conda Environment Configuration for EVCSAP Project
# Electric Vehicle Charging Station Allocation Problem (SP-EVCSAP)
#
# This environment provides all necessary dependencies for:
# - Stochastic programming optimization models
# - Geospatial data processing and visualization
# - Scientific computing and data analysis
# - Jupyter notebook development environment
#
# Installation:
#   conda env create -f environment.yml
#   conda activate evcsap
#
# Update:
#   conda env update -f environment.yml --prune

name: evcsap

channels:
  - conda-forge
  - plotly
  - idaes-pse
  - defaults

dependencies:
  # Python interpreter
  - python=3.8.*

  # Core scientific computing
  - numpy>=1.20.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - numexpr>=2.7.0
  - bottleneck>=1.3.0

  # Optimization and mathematical programming
  - pyomo>=6.0.0
  - ipopt>=3.14.0
  - cyipopt>=1.0.0
  - networkx>=2.6.0
  - sympy>=1.9.0

  # Geospatial analysis
  - geopandas>=0.11.0
  - fiona>=1.8.0
  - shapely>=1.8.0
  - folium>=0.13.0
  - geopy>=2.2.0
  - geographiclib>=1.52
  - mapclassify>=2.4.0

  # Data visualization
  - matplotlib>=3.5.0
  - plotly>=5.0.0
  - seaborn>=0.11.0
  - kaleido>=0.2.1

  # Jupyter ecosystem
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - ipykernel>=6.0.0
  - ipywidgets>=7.6.0
  - jupyterlab>=3.0.0
  - jupyterlab-widgets>=1.0.0

  # Data handling and I/O
  - openpyxl>=3.0.0
  - xlrd>=2.0.0
  - h5py>=3.0.0
  - pytables>=3.6.0

  # Web frameworks (for visualization dashboards)
  - flask>=1.1.0
  - flask-cors>=3.0.0

  # Development and testing
  - pytest>=6.0.0
  - pytest-cov>=2.0.0
  - black>=21.0.0
  - flake8>=3.8.0
  - isort>=5.0.0

  # Documentation
  - sphinx>=4.0.0
  - sphinx_rtd_theme>=0.5.0

  # Utilities
  - click>=7.0.0
  - tqdm>=4.60.0
  - joblib>=1.0.0
  - cloudpickle>=2.0.0
  - pint>=0.17.0

  # Security and authentication
  - cryptography>=3.0.0
  - argon2-cffi>=21.0.0

  # System utilities
  - psutil>=5.8.0
  - packaging>=21.0.0

  # pip-only packages
  - pip
  - pip:
    # Commercial solvers (license required)
    # - cplex>=22.1.0  # Uncomment if CPLEX license available
    # - gurobi         # Uncomment if Gurobi license available
    
    # Additional pip packages not available in conda
    - mpi-sppy>=0.11.0
    - idaes-pse>=2.0.0